import Head from "next/head";
import { createClient } from "next-sanity";
import { useState } from "react";

export default function Home({ priceData }) {
 
  const[discountType, setDiscountType] = useState()
  const[packingType, setPackingType] = useState()

  const handleSubmit = (e) => {
    e.preventDefault(),
    console.log(discountType, packingType)
  }

console.log(priceData)
  const allure6090 =
    ((priceData[2].size6090 + priceData[1].pillowMeterCost) *
      (priceData[1].AllureFabricPrice + priceData[3].transportcost) +
      (priceData[1].besheetStichingCost + priceData[1].pillowStitchingCost) +
      priceData[6].ld) * priceData[3].overhead;


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-2xl font-bold underline">Price Check</h1>
      <div className="bg-blue-100 p-5">
        <div className="bg-red-200 p-3 rounded-lg">
          A 60 x 90 : {allure6090}
        </div>
      </div>

      <div className="mx-auto flex w-full max-w-sm flex-col gap-6 p-5">
        <div className="flex flex-col items-center">
          {/* <h1 className="text-3xl font-semibold">Download Rate List</h1> */}
        </div>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <div className="form-field">
              <label className="form-label">Discount type</label>
              <select
                className="select"
                name="discountType"
                value={discountType}
                onChange={(e) => setDiscountType(e.target.value)}
              >
                <option value="glr">GLR</option>
                <option value="blr">BLR</option>
                <option value="slr">SLR</option>
                <option value="plr">PLR</option>
                <option value="c2c">C2C</option>
              </select>
            </div>
            <div className="form-field">
              <label className="form-label">Packing type</label>
              <div className="form-control">
                <select
                  className="select"
                value={packingType}
                  name="packingType"
                onChange={(e) => setPackingType(e.target.value)}
                >
                  <option value="stdpacking">Std. Packing</option>
                  <option value="ld">LD</option>
                  <option value="taiwan">Taiwan</option>
                  <option value="taiwanphoto">Taiwan + photo</option>
                </select>
              </div>
            </div>
            <div className="form-field pt-5">
              <div className="form-control justify-between">
                <button
                  type="submit"
                  className="btn btn-primary w-full font-bold"
                >
                  Download PDF
                </button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const client = createClient({
    projectId: "eo3yixtt",
    dataset: "production",
    useCdn: true,
  });

  const query = `*[]`;
  const priceData = await client.fetch(query);

  // Pass data to the page via props
  return { props: { priceData } };
}
